services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
