services:
  valkey:
    image: valkey/valkey
    ports:
      - 6379:6379

  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 8000:8000
    env_file:
      - .env.docker
    volumes:
      - ./uploads:/app/uploads
      - .:/app
      - /app/node_modules
    depends_on:
      - valkey
      - qdrant

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worker
    env_file:
      - .env.docker
    volumes:
      - ./uploads:/app/uploads
      - .:/app
      - /app/node_modules
    depends_on:
      - server
      - valkey
      - qdrant
    command: [ "pnpm", "dev:worker" ]
